### ISSUE TITLE
To verify user registration

### ISSUE THREAD

**Issue by lpark9** [lpark9/CozmoCrew#18]
Steps:
1.Run Emulator from Android Studio
2.Choose Device
3.Power on the device
4.Click "Register"
5.Input all data
6.Click "Register"

Expected:
User should be redirected to login page after completing registration.

**Comment by micahterrell** [comment]
Registration works, however some of the firebase errors are not handled. Not sure if this was on our docket for this sprint.

Also, instead of redirecting to login, I was redirected to college selection screen. This might actually be a feature instead of a bug ;)
